services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/transferring_things/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=transferring_things
      - POSTGRES_USER=dmitry
      - POSTGRES_PASSWORD=4221
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=transferring_things
      - POSTGRES_USER=dmitry
      - POSTGRES_PASSWORD=4221
    container_name: pgdb
    volumes:
      - ./data/db:/var/lib/postgresql/data


