# Generated by Django 4.2.7 on 2023-11-18 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='application',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bulletin_board.announcement', verbose_name='Объявление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bulletin_board.announcement', verbose_name='Объявление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Не нравится'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Нравится'),
        ),
    ]
